### ISSUE TITLE
Config error: can't split transformer namespace

### ISSUE THREAD

**Issue by stabenfeldt** [compose/transporter#110]
Hi,

I'm trying to set up a transporter between MongoDB and Elasticsearch.
I want to sync the entries collection in the harvester database in MongoDB. 
Is it `namespace: harvester.entries` it's complaining about? That looks sane too me. 

```bash
$ transporter run mongo-es.js
Mongo Config {URI:mongodb://172.17.0.32/harvester Namespace:harvester.entries 
Ssl:<nil> Timeout: Debug:true Tail:false Wc:0 FSync:false Bulk:false}
cannot create transformer adaptor (mongo/7e6b60a4-e4a1-49fe-7bb8-3da27b88b20a). 

CRITICAL: can't split transformer namespace 
(malformed namespace, expected a '.' deliminated string)
```

**mongo-es.js**

```
pipeline = Source({name:"mongo"})
  .transform({filename: "transformers/passthrough_and_log.js"})
  .save({name:"es", namespace: "harvester.entries"})
```

**config.yaml**
```
nodes:
  mongo:
    type: mongo
    uri: mongodb://172.17.0.32/harvester
    namespace: harvester.entries
    debug: true
  es:
    type: elasticsearch
    uri: http://172.17.0.34:9200/thisgetsignored
  logtransformer:
    filename: test/transformers/passthrough_and_log.js
    type: transformer
```

**Comment by Alino** [comment]
I would try to include namespace in transformer as well

```javascript
pipeline = Source({name:"mongo"})
  .transform({filename: "transformers/passthrough_and_log.js", namespace: harvester.entries})
  .save({name:"es", namespace: "harvester.entries"})
```

**Comment by jipperinbham** [comment]
@stabenfeldt, what @Alino suggested will definitely work. Right now, all nodes require a namespace. 

Since it was bit of a breaking change, we didn't want to make defaults for anything because a) we wanted people to be aware of the new feature b) we wanted to let the community help make the decision on when/where defaults should be set. 

For transformer functions, we're considering defaulting to letting all messages flow (i.e. `"namespace": "transformer./.*/"`) the first part of the namespace currently isn't used in transformer adapters.

**Comment by stabenfeldt** [comment]
@jipperinbham and @Alino, Thanks, that worked! :-)

**Comment by sunshineo** [comment]
Worked for me! Thanks!
