### ISSUE TITLE
MongoDB oplog tail to sync Elastic search doesn't work for remove operations.

### ISSUE THREAD

**Issue by wathmal** [compose/transporter#161]
I have setup transporter to sync mongoDB and Elastic search.
It's working perfectly fine to for document insertion operations in mongoDB. but if i delete a document from mongoDB it won't reflect the change on Elastic search.

Is there anything to change in application.js ??

**Comment by Alino** [comment]
as I know it is not possible with Transporter at the moment. That's why I abandoned Transporter and started [Mongo2ES](https://github.com/Alino/Mongo2ES) project, which has such feature to automatically remove documents from ES when they are removed from MongoDB (by default).

btw similar issue exists here https://github.com/compose/transporter/issues/62

**Comment by mkozjak** [comment]
If this gets done, I vote for a configurable option. Right now mongo-connector doesn't have this options and I need to move to something else.

**Comment by wathmal** [comment]
@mkozjak can I know what are the options supported by "mongo-connector" ?
does it support update queries?

**Comment by mkozjak** [comment]
@wathmal: It supports all actions. Anything you do on mongodb will get synced to the target system.

**Comment by Alino** [comment]
I didn't know about mongo-connector, looks interesting. Too late for me I am already using Mongo2ES on my project :) I am using it with ES 1.7.3 but CI tests are passing on ES 2.x, so I think it should work.

**Comment by jipperinbham** [comment]
fixed in the latest version [v01.2.](https://github.com/compose/transporter/releases/tag/v0.1.2)
