### ISSUE TITLE
elstic search creates autogenerated Id

### ISSUE THREAD

**Issue by edukondalugorla** [compose/transporter#216]
When i am trasforming  data from local mongodb  to elastic search with transporter elastic search creates an auto generated Id . but i am passing my custom id as _Id value.  how to store my custom id as _id in elastic server.  my elstic search version is 2.4

**Comment by JherezTaylor** [comment]
Do this in your transform file. 
```javascript
module.exports = function(msg) {
    id = msg.data._id['$oid']
    newdoc = _.omit(msg.data, ["_id"]);
    newdoc["id"] = id;
    msg.data = newdoc;
   return msg;
}
```
What's happening is that you are setting `_id` in the transform file, but deeper in the Go code `pkg/adaptor/rethinkdb/rethinkdb.go` they do this
```
doc["_id"] = doc["id"]
delete(doc, "id")
```

Which causes the BulkInsertError. It really isn't clear that you aren't supposed to pass `_id` at the transform level and I only came to that conclusion after multiple headaches. Elastic search will keep it's own autogenerated `_id` and the corresponding MongoDB `_id` will appear as `id`.

@jipperinbham Is it possible to update either the documentation or the example transform files with this? A lot of people are coming here from search engines and running into #209 and I suspect it's primarily because of this.

**Comment by jipperinbham** [comment]
@JherezTaylor I'll see about getting the examples updated as we work on getting #209 out. 

@edukondalugorla the suggested solution above should work so I'm going to close this issue out but please reopen if it does not meet your needs.

**Comment by JherezTaylor** [comment]
@jipperinbham Thanks much. Really appreciate the work that's being done.

**Comment by jipperinbham** [comment]
@JherezTaylor I've stubbed out READMEs for all current adaptors and pushed up to the experimental branch https://github.com/compose/transporter/tree/experimental#adaptors. We'll continue to use the adaptor specific READMEs to add notes/gotchas as issues come in.

**Comment by JherezTaylor** [comment]
@jipperinbham Nice, that should help out people coming in the future.
