### ISSUE TITLE
Elasticsearch sink namespace and type

### ISSUE THREAD

**Issue by kishorevarma** [compose/transporter#337]
HI,

Need Help,
I am using latest version of transporter, my pipline.js is as follow, I am facing problem to create the elastic search type, I am not sure where I do I need to provide, its creating type as `public.<postgres namespace>` (in this case public.errors) 

```
var source = postgres({
  uri:"host=postgres sslmode=disable dbname=exceptions user=postgres",
  debug: true,
  tail: true,
  replication_slot: "exception_replica_slot"
})

var sink = elasticsearch({
  uri: "http://elasticsearch:9200/exceptions",
});

t.Source("source", source, "errors")
  .Transform(pretty({}))
  .Save("sink", sink);
```

Even though I pass type as third argument to Save(`Save("sink", sink, 'errors'`)) its not working. 
Am I doing something wrong

**Comment by jipperinbham** [comment]
hi @kishorevarma, the elasticsearch adaptor will pull the type name from the originating source namespace which in your case is `public.errors`. The 3rd parameter to the `Source` and `Save` function is a namespace *filter* which is why the only table getting processed is `errors` but when postgresql sends the message down the pipeline, it sets the namespace to `public.errors`. Also, if a namespace filter is not provided then the default filter set is `.*` which is effectively a catch all.

In your case, you'll need to create a goja JS transformation function to alter the namespace before it reaches the elasticsearch adaptor. I plan to add a native one in the near future but for now, the following should work:

```javascript
var source = postgres({
  uri:"host=postgres sslmode=disable dbname=exceptions user=postgres",
  debug: true,
  tail: true,
  replication_slot: "exception_replica_slot"
})

var sink = elasticsearch({
  uri: "http://elasticsearch:9200/exceptions",
});

t.Source("source", source, "errors")
  .Transform(goja({"filename":"trim_ns.js"})
  .Transform(pretty({}))
  .Save("sink", sink);
```

and the `trim_ns.js` file would be:

```javascript
function transform(doc) {
    doc["ns"] = "errors";
    return doc
}
```

**Comment by kishorevarma** [comment]
Awesome explanation, I got it now. thanks @jipperinbham

**Comment by kishorevarma** [comment]
Hi @jipperinbham, another doubt not related to this issue, whats the difference between
goja and otto functions, I see both are same, I hope there might be some difference

**Comment by jipperinbham** [comment]
https://github.com/compose/transporter/wiki/Q%26A

**Comment by kishorevarma** [comment]
Awesome , I am closing issue now
