### ISSUE TITLE
Running javascript with Mongodb collection_filters

### ISSUE THREAD

**Issue by ebaizel** [compose/transporter#339]
Within the `collection_filters` of Mongodb adaptor, is it possible to run javascript?  Specifically, we'd like to check for documents with a `_id` within a certain date range.

For example, from the Mongo shell if we wanted to only get users that had an _id timestamp from before 10/1/2015, we would issue:

`db.users.find({_id:{$lt: ObjectId(Math.floor((new Date('2015/10/01'))/1000).toString(16) + "0000000000000000")})`

I tried converting this to the collection_filters syntax with this:
"{\"users\": {\"_id\":{\"$lt\": ObjectId(Math.floor((new Date('2015/10/01'))/1000).toString(16) + \"0000000000000000\")}}}"

but got an error complaining about the `command_filters` being invalid.

would you expect this to work?

**Comment by jipperinbham** [comment]
that's a pretty complex query and that will definitely not work yet but it's definitely something I think transporter could/should support. 

I'm going to tag this as an enhancement and I may be able to get to it soon since I had already planned on converting the `collection_filters` from a string to a JSON object soon.

**Comment by sashaaKr** [comment]
@jipperinbham is there any plans to add this functionality?
