### ISSUE TITLE
Transport sort order starting with most recent

### ISSUE THREAD

**Issue by ebaizel** [compose/transporter#353]
Is there a way to kick off the transporter so that it starts with migrating the most recent documents and works back to the beginning of time?  Or is it fixed to always go from start to current time?

**Comment by jipperinbham** [comment]
it's always fixed to start with the oldest documents in order to support being able to resume from where it left off should an issue occur while querying. 

I imagine it would be possible to start from the newest document and work its way backwards and then do a second iteration starting with what was the newest document and work forwards but I'd worry it'd complicate the process a bit too much.

**Comment by jipperinbham** [comment]
closing this as I don't see it fitting in with the current design
