### ISSUE TITLE
Resume operations after being stopped

### ISSUE THREAD

**Issue by alexandrefabre22** [compose/transporter#446]
**As of release v0.4.0, transporter contains support for being able to resume operations after being stopped.**

I am using transporter (last commit on master version 3f298eb1d2e1d2f1c43130370e5dc98cdcda6fb7) to transfer data from MongoDB  (with tailing oplogs) to Rabbitmq, so normally I can use this functionality. 

But I have the following problems:
1. When I am using xlog_dir option, I have no log files in the directory. I feel like nothing is going on.
2. When I am using log_dir, log files are created in the directory. But when I stop and resume, after reading already transfered data from log files, it cannot transfer other data.
3. Furthermore, log files created from log_dir take a lot of space... too huge to be used in production environment. I do not understand why you cannot save the last timestamp of the mongo oplogs. 

Do you have any advice to use the resume functionnality ? 
Thanks.

**Comment by jipperinbham** [comment]
thanks for the details of what you're experiencing!

> 1. When I am using xlog_dir option, I have no log files in the directory. I feel like nothing is going on.

There's a typo in the README that needs to be updated, the correct option is `log_dir`.

> 2. When I am using log_dir, log files are created in the directory. But when I stop and resume, after reading already transfered data from log files, it cannot transfer other data.

Can you provide the `pipeline.js` with any sensitive information removed? The resume functionality has been tested a good bit so without the pipeline or any logs it's hard to say what could be happening.

> 3. Furthermore, log files created from log_dir take a lot of space... too huge to be used in production environment. I do not understand why you cannot save the last timestamp of the mongo oplogs.

This can be configured by setting the `compaction_interval` in `t.Config` to a much shorter duration than the default of 1hr. We have to store the full records because the commit log is a general purpose log that works for all adaptors, not jut MongoDB.
