### ISSUE TITLE
Elasticsearch 6.x compatibility

### ISSUE THREAD

**Issue by johnjjung** [compose/transporter#463]
This Issue is for elasticsearch 6.x compatibility.

## Bug report
transporter currently does not support elasticsearch 6.x

### System info:

- Transporter version: 0.5.2
- OS: developing on mac, running on linux
- DB version: elasticsearch 6.x

## Feature Request

There are some elasticsearch syntax changes from 5.x to 6.x and it doesn't seem to be that drastic.
I'm starting this Issue to discuss plan of actions for PR

### Proposal:

Things I'll need to update:

- `adaptor/elasticsearch/clients/v6`
  - https://gopkg.in/olivere/elastic.v6 seems to exist so porting writer files doesn't seem too bad, glide file will probably get updated
- `config/clients/v6`
  - it seems like these are just configs for testing (will probably need help from main contributors)
- `scripts/before_scripts.sh`
  - line 17 - 19 seems to use configs
- parent child config
  - docs need to be updated as well because creating the parent child mappings are also different
- test for 6.x (I'll need help from maintainers to get these to pass)
  -  I'd like to use a docker-compose file to make these test locally but travis needs configs

**Comment by johnjjung** [comment]
Hi, I think I was waiting on the compose team to comment, but I can take a look again to see what it will take

**Comment by ricardolimaui** [comment]
a lot of libraries were not getting any updates to elasticsearch 6.X :/ I'm also facing this issue

**Comment by qakart** [comment]
I am also waiting for 6.x support ,please let me know ,if you need any help i will contribute

**Comment by qakart** [comment]
thanks @johnjjung  i will do it please guide me which library and where to update

**Comment by qakart** [comment]
this is the proposed one right?

adaptor/elasticsearch/clients/v6
https://gopkg.in/olivere/elastic.v6 seems to exist so porting writer files doesn't seem too bad, glide file will probably get updated
config/clients/v6
it seems like these are just configs for testing (will probably need help from main contributors)
scripts/before_scripts.sh
line 17 - 19 seems to use configs
parent child config
docs need to be updated as well because creating the parent child mappings are also different
test for 6.x (I'll need help from maintainers to get these to pass)
I'd like to use a docker-compose file to make these test locally but travis needs configs
