### ISSUE TITLE
**panic: Got unknown index key type for field user_id**

### ISSUE THREAD

**Issue by d4rqu** [compose/transporter#485]
Hello,

This is my pipeline:

**var source = mongodb({
  "uri": "${MONGODB_URI}",
  // "timeout": "30s",
  // "tail": false,
  // "ssl": false,
  // "cacerts": ["/path/to/cert.pem"],
  // "wc": 1,
  // "fsync": false,
   "bulk": true,
  // "collection_filters": "{}",
   "read_preference": "Primary"
})

var sink = elasticsearch({
  "uri": "${ELASTICSEARCH_URI}"
  // "timeout": "10s", // defaults to 30s
  // "aws_access_key": "ABCDEF", // used for signing requests to AWS Elasticsearch service
  // "aws_access_secret": "ABCDEF" // used for signing requests to AWS Elasticsearch service
  // "parent_id": "elastic_parent" // defaults to "elastic_parent" parent identifier for Elasticsearch
})

t.Source("source", source, "/^abonent$/").Save("sink", sink, "/.*/")**

i get error:
**panic: Got unknown index key type for field user_id**

Please help.

**Comment by johnnason** [comment]
Greetings. I had hit this some time back as well.

First, the "panic" comes from the mongo db driver. I have an accepted PR from that team (https://github.com/globalsign/mgo/pull/298) but it's not in a release yet.

I also have a workaround PR in transporter (https://github.com/compose/transporter/pull/479) but I hesitated on merging it, since I felt the problem was better fixed in MGO. Perhaps I'll still merge it tho.

Lastly, you can simply use a mongo shell to connect to your DB and delete the offending index. If it's causing this error, it's 99% a bad index anyway.
