### ISSUE TITLE
Transformers don't seem to be able to drop messages

### ISSUE THREAD

**Issue by codepope** [compose/transporter#93]
In 0.0.4, passing the better Msg object - and having to return it - means you can't return false - it generates an error message.

 In previous versions, returning false (or some other non map/interface type) would mean the message was dropped from the pipeline.

**Comment by jipperinbham** [comment]
Good call, I think the best way to handle this is to create a new `OpType` of `Noop` that we can then check before sending the message downstream. Thoughts?

**Comment by codepope** [comment]
Sounds good - it has to be n Noop (as d for Drop is taken by Delete :) )...

**Comment by jipperinbham** [comment]
ha, good call, also, I'm not seeing where the codebase supported the ability to drop messages in transformer functions, can you show me an example where you had this working?

**Comment by codepope** [comment]
https://www.compose.io/articles/transporter-transformers-powering-up-your-data-transfer/

Creating and Skipping and Counting... These worked with hosted transporter, but I think I need to consult with Nick on the history.

**Comment by codepope** [comment]
I think we're talking effective side effect which has just iterated out, so bringing it back officially as Noop would be most excellent.

**Comment by jipperinbham** [comment]
Looking back through the changes to `transformer`, the ability to skip documents was removed here, https://github.com/compose/transporter/commit/2682b0854358d3e390ce61146f3390da6f9af951, when we changed from `msg.Document` to `msg.Data` and the type went from `map[string]interface{}` to `interface{}`. I've added this to the next milestone release since it's more of an enhancement we want to bring back and less of a bugfix.

**Comment by nstott** [comment]
:+1: good plan
